import { Vertex, bfsTraverse } from "./graph.mjs";

const a = new Vertex("a");
const b = new Vertex("b");
const c = new Vertex("c");
const d = new Vertex("d");
const e = new Vertex("e");
const f = new Vertex("f");
const g = new Vertex("g");
const h = new Vertex("h");
const i = new Vertex("i");
const j = new Vertex("j");
const k = new Vertex("k");
const l = new Vertex("l");
const m = new Vertex("m");
const n = new Vertex("n");
const o = new Vertex("b");
const p = new Vertex("p");

a.addAdjacentVertext(b);
a.addAdjacentVertext(c);
a.addAdjacentVertext(d);
b.addAdjacentVertext(f);
b.addAdjacentVertext(e);
c.addAdjacentVertext(g);
d.addAdjacentVertext(h);
d.addAdjacentVertext(i);
e.addAdjacentVertext(b);
e.addAdjacentVertext(j);
f.addAdjacentVertext(j);
f.addAdjacentVertext(b);
g.addAdjacentVertext(c);
g.addAdjacentVertext(k);
h.addAdjacentVertext(l);
h.addAdjacentVertext(m);
h.addAdjacentVertext(d);
i.addAdjacentVertext(m);
i.addAdjacentVertext(d);
i.addAdjacentVertext(n);
j.addAdjacentVertext(o);
j.addAdjacentVertext(e);
j.addAdjacentVertext(f);
k.addAdjacentVertext(g);
l.addAdjacentVertext(h);
m.addAdjacentVertext(h);
m.addAdjacentVertext(i);
n.addAdjacentVertext(p);
n.addAdjacentVertext(i);

bfsTraverse(a);
